# Generated by Django 3.1.4 on 2021-02-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='toy',
            old_name='tag',
            new_name='tags',
        ),
    ]
