# Generated by Django 3.1.4 on 2021-02-28 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0003_auto_20210228_2225'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
    ]
