# Generated by Django 3.1.4 on 2021-03-01 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0004_remove_address_country'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='employee',
            field=models.ManyToManyField(related_name='companys', to='toys.Employee'),
        ),
    ]
