# Generated by Django 3.1.4 on 2021-02-26 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0005_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='toy',
            name='price',
            field=models.DecimalField(decimal_places=2, default=38.98, max_digits=10),
            preserve_default=False,
        ),
    ]
