# Generated by Django 3.1.4 on 2021-03-01 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0005_auto_20210301_1817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='employee',
        ),
        migrations.AddField(
            model_name='employee',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='toys.company'),
        ),
    ]
