# Generated by Django 3.1.4 on 2021-03-05 06:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import toys.models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0007_auto_20210301_2047'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='address',
            options={'verbose_name_plural': 'Address'},
        ),
        migrations.AlterModelOptions(
            name='toy',
            options={'verbose_name_plural': 'Toys'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name_plural': 'Users'},
        ),
        migrations.AddField(
            model_name='toy',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=toys.models.logo_upload_path),
        ),
        migrations.AddField(
            model_name='toy',
            name='type',
            field=models.CharField(blank=True, choices=[('animals', 'Animals'), ('dolls', 'Dolls'), ('cars', 'Cars'), ('educational_toys', 'Educational Toys'), ('electronic_toys', 'Electronic Toys')], max_length=16, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 3, 5, 6, 34, 30, 977560, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
