# Generated by Django 3.1.4 on 2021-03-11 03:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0010_auto_20210311_0731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='email',
        ),
    ]
