# Generated by Django 3.1.4 on 2021-03-11 03:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toys', '0011_remove_company_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
